### ISSUE TITLE
Problems configuring my project

### ISSUE THREAD

**Issue by danielmessi13** [oguzhnatly/flutter_carplay#3]
Hi, first of all congratulations for the initiative, I'm wanting to use your package, I had problems inserting it in the project I'm working on so I created a new project using Flutter 2.5

So, I followed all the steps, with the exception of "Entitlements.plist", as I haven't received the rights from Apple yet.

I'm getting these two errors when trying to build:

![image](https://user-images.githubusercontent.com/29608634/134523760-96de55b1-455f-4cf0-acc7-32fc8961a69d.png)

I downloaded the example project and got it running, so I checked a few things different from what is said in Readme.

In example, in the Podfile file this line is still commented out: # platform :ios, '9.0'

By Xcode it also says that iOS Deployment Target is 9.0

- flutter doctor -v
 
![image](https://user-images.githubusercontent.com/29608634/134524099-a4f37646-d04a-436d-bfc6-56b0e507ef76.png)

**Comment by danielmessi13** [comment]
If it helps here is the new project I created:
https://github.com/danielmessi13/carplay_test

**Comment by oguzhnatly** [comment]
Hey @danielmessi13, thank you for your support and message. I really appreciate it!

Also, thanks for providing the Github project repository. I've cloned your project and confirmed that you've done everything correctly. Since you're using the `main.dart` file, which is the same as the example project, you need to copy the flutter logo image from [images folder](https://github.com/oguzhnatly/flutter_carplay/tree/master/example/images). Because as you can see [here](https://github.com/danielmessi13/carplay_test/blob/ab9e6f8347064dbac75173a2fc82d47619c2d517/lib/main.dart#L41), the app was trying to show an image from flutter assets that did not exist. That's why it's crashing. 🙂 

Remember to include the image path in the `pubspec.yaml` file. 
![Screen Shot 2021-09-23 at 23 18 31](https://user-images.githubusercontent.com/54781138/134577870-dd57aed0-5ed8-4b2b-bad7-98ce10020915.png)

---

However, after importing the image, your app is going to run without error, but it will not connect to the CarPlay simulator due to the missing Entitlements.plist, as you have already mentioned. CarPlay requires this entitlement file and one of the entitlement keys. It has nothing to do with this package, it is required for everything to create an app in CarPlay. It does not matter whether you have or have not received entitlement keys from Apple. 

> Whether you are running the app through a simulator or developing it for distribution, you must ensure that the relevant entitlement key is added to the Entitlements.plist file. You must create an Entitlements.plist file if you do not already have one. - README.md

But don't worry! You can create your own Entitlements. It's very simple to create an entitlements file to run CarPlay in a simulator:

1. Open `ios/Runner.xcworkspace` in Xcode.
2. Open Signing & Capabilities tab in Runner project.
3. Add a capability by clicking to `+ Capability` button at the top-right corner.
4. Select `Keychain Sharing`. Then you will see that the entitlements file will be created in the Runner folder.
5. Open the entitlements file and delete the keychain access groups if you want. Then add an entitlement key, for example `com.apple.developer.carplay-maps`. You can find more detail [here](https://developer.apple.com/documentation/carplay/requesting_the_carplay_entitlements).

![Screen Shot 2021-09-23 at 23 30 52](https://user-images.githubusercontent.com/54781138/134579823-a8b1c881-f89d-4102-ad58-de90e5e4224d.png)
![Screen Shot 2021-09-23 at 23 33 42](https://user-images.githubusercontent.com/54781138/134579825-c8f6d83b-58fb-4f83-8b89-6f65a53ff7ca.png)

That was all; your app is now ready to go 🚀 Please let me know if you have any further questions!

**Comment by EArminjon** [comment]
Add this in the doc home page :)
