### ISSUE TITLE
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: Class 'CPListTemplate' has no instance getter 'templates'.

### ISSUE THREAD

**Issue by danielmessi13** [oguzhnatly/flutter_carplay#4]
When having a CPListTemplate as "rootTemplate", methods such as "self.setDetailText" cause this error:

`[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: Class 'CPListTemplate' has no instance getter 'templates'.`

![image](https://user-images.githubusercontent.com/29608634/135325545-22a3f48f-d132-4068-8266-4328ff83cf68.png)

Repository:
https://github.com/danielmessi13/carplay_test

**Comment by oguzhnatly** [comment]
Hey @danielmessi13, thank you for reporting this bug. It's the first one 🎉 and I really appreciate it! 

It will be fixed in the next minor version update. If you or anyone is interested in and wants to fix and contribute ASAP, send me [an email](mailto:info@oguzhanatalay.com?subject=Contribute%20flutter_carplay%20#4%20issue) or a pull request. I'll let you know when it's released.

**Comment by oguzhnatly** [comment]
Hey @danielmessi13, thank you for reporting this bug. It's the first one 🎉 and I really appreciate it! 

It will be fixed in the next minor version update. I'll let you know when it's released. If you or anyone is interested in and wants to fix and contribute ASAP, send me [an email](mailto:info@oguzhanatalay.com?subject=Contribute%20flutter_carplay%20#4%20issue) or a pull request.

**Comment by oguzhnatly** [comment]
Hey @danielmessi13, the issue has been solved and version 1.0.1 is published in pub.dev, see [here](https://pub.dev/packages/flutter_carplay). Keep going!
